### ISSUE TITLE
Support for null-terminated strings

### ISSUE THREAD

**Issue by Namek** [getty-zig/json#23]
### Description

It kinda-works when there is just enough bytes:
```zig
const string = json.toPrettySlice(allocator, .{.val = utils.allocCString(allocator, "Talk", 5)}) catch unreachable;
```
The word "Talk" is 4 letters but we need the 5th byte for null termination. And the result is:
```json
{
  "val": "Talk\u0000"
}
````
not perfect because it shows the null value as a unicode character.

Now, let's go for one more byte:
```zig
const string = json.toPrettySlice(allocator, .{.val = utils.allocCString(allocator, "Talk", 6)}) catch unreachable;
```
which fails for a null-terminated string because of the utf8 validation check:
```
thread 198568 panic: attempt to unwrap error: Syntax
[...]
\json-getty-zig-github.com-9f451bd8\pkg\src\ser\serializer.zig:123:17
```

I wish I could at least patch it somehow with a custom Serialization Block. The reason I use C-strings is the Dear ImGui library. I allocate bigger strings upfront for text input UI elements.

### How to Reproduce the Bug

Zig 0.9.1

```zig
const std = @import("std");
const json = @import("json");

pub fn allocCString(allocator: std.mem.Allocator, comptime text: []const u8, bufSize: u32) [:0]u8 {
    var buf = allocator.allocSentinel(u8, bufSize, 0) catch unreachable;
    _ = std.fmt.bufPrintZ(buf, text, .{}) catch unreachable;
    return buf;
}

var gpa: std.heap.GeneralPurposeAllocator(.{}) = std.heap.GeneralPurposeAllocator(.{}){};
pub fn main() void {
    gpa.init();
    defer _ = gpa.deinit();
    var allocator = gpa.allocator();

    var strr = utils.allocCString(allocator, "Talk", 6); // it's OK-ish for 5, throws error with 6
    defer allocator.free(strr);

    const string = json.toPrettySlice(allocator, .{.val = strr}) catch unreachable;
    defer allocator.free(string);

    std.debug.print("{s}\n", .{string});
}
```

### Additional Context

The current implementation of a string support is:
```zig
fn serializeString(self: *Self, value: anytype) Error!Ok {
    if (!std.unicode.utf8ValidateSlice(value)) {
        return Error.Syntax;
    }

    self.formatter.beginString(self.writer) catch return Error.Io;
    escape(value, self.writer, self.formatter) catch return Error.Syntax;
    self.formatter.endString(self.writer) catch return Error.Io;
}
```

**Comment by phan-do** [comment]
Is slicing `strr` an option for you? If so, you can simply omit the extra bytes:

```zig
const string = json.toPrettySlice(allocator, .{.val = strr[0..5]}) catch unreachable;
```

In any case, sentinel termination in Getty is sort of unfinished so I'm not too surprised about stuff like this coming up.

**Comment by Namek** [comment]
not really, I have lots of such strings in my structure (tree of structs). Any ideas on how would you like to implement this? Without that, I'd have to do the whole serialization manually so I'd like to move it forward if I'm able to.

EDIT: provided the PR #24

**Comment by ibokuri** [comment]
Now that I think about it, in `allocCString`, I think filling out `buf` will null characters before you update it with your text would solve your issue.

**Comment by phan-do** [comment]
Okay, after a bit of thought, I don't think there's anything actually wrong with Getty JSON here.

- Serializing `utils.allocCString(allocator, "Talk", 5)` succeeds, as it should.
- Serializing `utils.allocCString(allocator, "Talk", 6)` fails, *as it should*. The 5th element is undefined memory AFAIK, which I believe is what is triggering the UTF-8 validation to fail. In any case, if the `std` doesn't consider it a valid UTF-8, then neither should the library.

As for how to get around this, you can define a Serialization Block for sentinel-terminated slices (the type returned from `allocSentinel`). In the block, you'd serialize them however you want (e.g., `std.mem.sliceTo` or whatever). Then, instead of serializing your struct with `toSlice`, you can use `toSliceWith` and pass in your block. Everything else will be serialized as normal, but sentinel-terminated slices will be serialized how you specified.

**Comment by Namek** [comment]
Just to be on the same page: `utils.allocCString(allocator, "Talk", 6)` is like this: `["T", "a", "l", "k", 0, 0]`
The last byte is a sentinel from a language, and the previous one is provided by the `std.fmt.bufPrintZ` (Z for additional sentinel right after the given string).

I thought it was impossible to define a SB for strings. I'll try it somewhat later and get back to this issue.

**Comment by phan-do** [comment]
Ah okay, that makes sense why the PR worked then.

But yeah, an SB would probably be the best solution for your case since you got many of those pre-allocated strings.

**Comment by Namek** [comment]
OK, so I went with SB:
```zig
pub const ser_cStrings = struct {
    pub fn is(comptime T: type) bool {
        return comptime std.meta.trait.isZigString(T);
    }

    pub fn serialize(value: anytype, serializer: anytype) @TypeOf(serializer).Error!@TypeOf(serializer).Ok {
        var slice = std.mem.sliceTo(value, 0);// just the quickest workaround
        return try serializer.serializeString(slice);
    }
};
```

but for **deserialization** I'm a bit puzzled:
```
W:\dev\definitive_dialoguer\.gyro\getty-getty-zig-github.com-ec22fc44\pkg\src\de\impls\visitor\slice.zig:52:37: error: expected type 'error{DuplicateField,InvalidCharacter,InvalidControlCharacter,InvalidEscapeCharacter,InvalidLength,InvalidLiteral,InvalidNumber,InvalidSeparator,InvalidTopLevel,InvalidTopLevelTrailing,InvalidType,InvalidUnicodeHexSymbol,InvalidUtf8Byte,InvalidValue,InvalidValueBegin,InvalidValueEnd,MissingField,MissingVariant,OutOfMemory,Overflow,TooManyClosingItems,TooManyNestedItems,UnbalancedBraces,UnbalancedBrackets,UnexpectedClosingBrace,UnexpectedClosingBracket,UnexpectedEndOfJson,UnknownField,UnknownVariant,Unsupported}![:0]u8', found '[]u8'
            return if (Child == u8) input else error.InvalidType;
                                    ^~~~~
W:\dev\definitive_dialoguer\.gyro\getty-getty-zig-github.com-ec22fc44\pkg\src\de\impls\visitor\slice.zig:37:127: note: function return type declared here
        fn visitString(_: Self, allocator: ?std.mem.Allocator, comptime Deserializer: type, input: anytype) Deserializer.Error!Value {
                                                                                                            ~~~~~~~~~~~~~~~~~~^~~~~~
```

when I provide just this simple struct:
```zig
const Omg = struct {
    name: [:0]u8,
};
```

**Comment by Namek** [comment]
Just before the errored line I've put a few logs:

```zig
@compileLog(Child);
```
```
@as(type, u8)
```
and
```zig
@compileLog(Value);
```
```
@as(type, [:0]u8)
```
and
```zig
@compileLog(@typeInfo(Value));
```
```
@as(builtin.Type, .{ .Pointer = .{.size = .Slice, .is_const = false, .is_volatile = false, .alignment = 1, .address_space = .generic, .child = u8, .is_allowzero = false, .sentinel = 0} })
```

My only conclusion is that the call `const Child = std.meta.Child(Value);` looses info about sentinel.

**Comment by phan-do** [comment]
I think the problem is that the `visitString` method of the slice visitor doesn't handle sentinels. It's trying to return a `[]u8` (or `[]const u8`, I forget) when the return type in this case is a `[:0]u8`, and the former doesn't implicitly cast to the latter.

[`std.json` has some special logic to handle this case](https://github.com/ziglang/zig/blob/master/lib/std/json.zig#L1689-L1693), so I think this should be an easy fix. Just a bit of copying and pasting.

**Comment by phan-do** [comment]
I'll close this issue for now since the initial problem you pointed out (serialization of null-terminated strings) seems to be solved now. If you have any other questions though, feel free to reopen.

In the meantime, I'll make a separate ticket for the deserialization case.
