### ISSUE TITLE
Conditionally omit specific fields of a struct

### ISSUE THREAD

**Issue by Namek** [getty-zig/json#25]
There are situations where I want to completely omit some fields of a struct (or all structs).

Examples:
- for a logical model, with a runtime condition, don't emit fields that are UI-specific
- don't emit some pointers, e.g. OpenGL context data
- `allocator` field stored in the model

In my case I wish to export the model in 2 modes, chosen dynamically by a user:
1. full
2. only logical data

Consider this example struct:

```zig
pub const CanvasNode = struct {
    id: c_int,
    name: []u8,

    // these fields are to be omitted in the logical export mode
    pos: c.ImVec2 = .{ .x = 0, .y = 0 },
    size: c.ImVec2 = .{ .x = 250, .y = 300 },
};
```

Is there anything like that or any idea where I could provide such a mechanism?

**Comment by phan-do** [comment]
You can make however many serialization blocks you want and then swap between them at runtime.

```zig
const getty = @import("getty");
const json = @import("json");

// define CanvasNode...

// This block omits the `pos` and `size` fields.
const skip_vecs_sb = struct {
    pub fn is(comptime T: type) bool {
        return T == CanvasNode;
    }

    pub fn serialize(value: anytype, serializer: anytype) !@TypeOf(serializer).Ok {
		var s = try serializer.serializeStruct("CanvasNode", 2);
        const st = s.structure();

        try st.serializeField("id", value.id);
        try st.serializeField("name", value.name);

        return try st.end();
    }
};

pub fn main() !void {
	var want_logical_form: bool = user_input();
	var c = CanvasNode{...};


    if (want_logical_form) {
		_ = try json.toSliceWith(std.heap.page_allocator, c, block);
    } else {
		_ = try json.toSlice(std.heap.page_allocator, c);
	}
}
```

**Comment by Namek** [comment]
The code above actually picks specific fields to serialize rather than omitting the other ones. So whenever I change my structure I have to also change the serializer. I'll see whether that suffices, thanks :)

**Comment by phan-do** [comment]
That was just the easiest way to show you what I meant. Usually you'd loop over all the fields in the struct type and then ignore any fields that match a name or type or whatever.

**Comment by Namek** [comment]
in case anyone would be looking for a tiny more general solution, this is my serialization block for a `model.WorldState` type omitting the `id_gen` field:
```zig
pub const ser_modelWorld = struct {
    pub fn is(comptime T: type) bool {
        return comptime T == model.WorldState;
    }

    pub fn serialize(value: anytype, serializer: anytype) !@TypeOf(serializer).Ok {
        const T = @TypeOf(value);
        const fields = std.meta.fields(T);

        var s = try serializer.serializeStruct(@typeName(T), fields.len);
        const st = s.structure();
        inline for (fields) |field| {
            if (!std.mem.startsWith(u8, field.name, "id_gen")) {
                try st.serializeField(field.name, @field(value, field.name));
            }
        }
        return try st.end();
    }
};
```
