### ISSUE TITLE
Pre-allocated, sentinel-terminated strings are invalid UTF8 slices

### ISSUE THREAD

**Issue by phan-do** [getty-zig/json#32]
### Description

Sentinel-terminated buffers are often preallocated with extra memory to minimize allocations. For example, a buffer may have space for 10 elements, but only 3 of those elements are actually filled (4th element is a sentinel and the rest are undefined).

Currently, such buffers when serialized as a string (e.g., `[:0]u8`) return `error.Syntax`. That's because `serializeString` calls `std.unicode.utf8ValidateSlice`, which returns `false` since it's looking at the entire buffer, which _is_ an invalid UTF8 slice. However, we shouldn't look at the whole buffer, just up until the sentinel.

We _should_ be able to add in `serializeString` a call to `std.mem.indexOfSentinel` to find the sentinel position for incoming sentinel-terminated strings. Then, we can properly slice the incoming string using that position and pass it along to `utf8ValidateSlice` like normal. Non-sentinel-terminated strings will just be processed like they are now.

### How to Reproduce the Bug

```zig
const std = @import("std");
const json = @import("json");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();
    defer _ = gpa.deinit();

    var value = allocCString(allocator, "abc", 10);
    defer allocator.free(value);

    const slice = try json.toSlice(allocator, value); // error.Syntax
    defer allocator.free(slice);

    std.debug.print("val: {any}\n", .{value});
    std.debug.print("str: {s}\n", .{slice});
}

fn allocCString(allocator: std.mem.Allocator, comptime text: []const u8, bufSize: u32) [:0]u8 {
    var buf = allocator.allocSentinel(u8, bufSize, 0) catch unreachable;
    _ = std.fmt.bufPrintZ(buf, text, .{}) catch unreachable;

    return buf;
}
```

**Comment by Namek** [comment]
@ibokuri  shouldn't we have a separate serialization block for this?

**Comment by phan-do** [comment]
Good point. This would be better as a fix in Getty instead of Getty JSON. That way, all serializers can benefit from it.

We don't need a whole new SB though, we can just update the default string SB to properly slice sentinel-terminated strings. I'll dupe this issue over on the Getty repo and close this one.

Thanks! 

edit: https://github.com/getty-zig/getty/issues/99

**Comment by ibokuri** [comment]
https://github.com/getty-zig/getty/issues/99
